### ISSUE TITLE
How can i use zipkins for tracing?

### ISSUE THREAD

**Issue by alex023** [AsynkronIT/protoactor-go#191]
i found ```actor/middleware/protozip/outbound_middleware.go```,can get header for tracing. But the header need init, so:
1. how can i preset  **trace-id/span-id/child-id** before inbound when use **pid.Tell** or **pid.Request** method?
2. how can i transfer trace-id and other information by MessageHeader between different node?

**Comment by feyman2016** [comment]
I'm playing protoactor with zipkin currently.
1. For now, the inbound middleware cannot set the readonly `MessageHeader`, you can try to set the MessageHeader in the outbound Middleware.
2. I think the trace info propagation should be implemented by `MessageHeader`  between actors, but the `MessageHeader` for now is not available , because it uses a global variable for `emptyMessageHeader`

**Comment by PotterDai** [comment]
Fixed here https://github.com/AsynkronIT/protoactor-go/pull/206
