### ISSUE TITLE
Keep reference to responder PID after actor.Request().

### ISSUE THREAD

**Issue by iwasaki-kenta** [AsynkronIT/protoactor-go#238]
By initiating a Request() remotely, it seems that a responding actor takes a reference of the PID of the requesting actor but not vice versa.

By dereferencing `actor.Context.Sender()` on the requesting actor, it will resolve into nil.

The only way so far from what I see in the repository to have the requester get a reference to the PID of the responder is to keep a reference of an actor.PID inside the response message's protobuf.

The alternative is to always keep a reference to the responder's PID.

**Comment by rogeralsing** [comment]
I'm not quite following.

ActorA requests from ActorB : ActorB.Sender is now ActorA
ActorB responds to ActorA : ActorA.Sender is now nil <- is this what what you are saying?

**Comment by iwasaki-kenta** [comment]
Yep, that's what seems to be the case. I could create a quick sample case if it's unexpected behavior.

**Comment by rogeralsing** [comment]
No this is by design.

if you call `RequestFuture`, then you already know the pid of the actor you are talking to.
And you get the response back once the future completes.

If the question is more in terms of "why don't every message have a sender", this is for performance reasons, as there is a cost to passing the sender.
in Remote scenarios, this means we need to pass the identity of the sender for each message if required.
it also carries a semantic meaning that implies that the receiver for some reason need to know about the sender.

We simply decided to not pass sender due to both of the above reasons, and instead only include it for Requests.

If you need to pass back a sender in a Request scenario.
I would say just explicitly passing back the sender in the response message would be the most straight forward solution.

if you are using `Request`(not `RequestFuture`), you could also respond by using
`context.Request(context.Sender(), response)`

Somewhat hacky, but it would do what you want, it sends the response back to the sender. and Request will include the sender. so you get both the response and the sender.

Does this help?

**Comment by rogeralsing** [comment]
To shed some light on the last part.

a `context.Respond` is just a short form for `context.Tell(context.Sender(), message)`
And `context.Request` is a just a short form for `context.Tell(pid, &MessageEnvelope {Sender: sender, Message: message})`

So they are all just variations of Tell.

**Comment by iwasaki-kenta** [comment]
Perfect, thanks a lot.
