### ISSUE TITLE
How to broadcast to grains ?

### ISSUE THREAD

**Issue by otherview** [AsynkronIT/protoactor-go#286]
Similar to https://github.com/AsynkronIT/protoactor-go/issues/62 

Would like to broadcast messages to grains, probably by Type or some sort of play on the id.

Could anyone point me in the right directions ?

Right now I'm going around this by having a RegisterGrain that knows the addresses of the Grains I want to broadcast to. But this seems like a bad idea..

Thanks!

**Comment by PotterDai** [comment]
That's actually how I did it in my use case as well, and for more advanced situation, I just use NATS.

Basically this is something Cluster currently lacking, grain subscribe to a certain topic and you just send message to that topic, all grains subscribe to that topic will receive the message. Would love to implement it, but I didn't see much urgency in my use case since NATS just satisfied my needs.

**Comment by otherview** [comment]
Nifty!

I didn't know about NATS - the only thing stopping me from using it right now is building another layer just for broadcasting. Does look cool though 👍 

Was thinking of adding an `service.name+"Async"` in the protos generator because most of the broadcasts I don't want to wait for a reply.
Could probably spawn one go routine per call (when broadcasting) too.. Ooc how did you handle that ?

**Comment by PotterDai** [comment]
Actually I just took codes from here
https://github.com/AsynkronIT/protoactor-go/blob/bc94063062fd455093e27d8b6dce42d00d00f37b/examples/cluster-metrics/shared/protos_protoactor.go#L53-L62
and replace `RequestFuture` with `Request` in the last line. Since it's a very specific use case that does not happen pretty often, so bypassing the code-gen is not a lot of work in my use case. = )

**Comment by otherview** [comment]
Much appreciated! :)
