### ISSUE TITLE
Good defaults

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-go#83]
I would like to see that we come up with some good defaults that we all can agree on being the right choice for various parts of actors.

### Default supervision strategy

What do we want, Kill after x restarts or exponential back-off ?

Killing makes sense in the way that having broken actors floating around is pointless.
Exponential back-off makes sense in the way that many errors are transient and just waiting might solve them.

### Default Mailbox type

We currently use the unbounded mailbox, unbounded queues are notoriously bad for systems at scale.
IMO, we should introduce a new queue, built on the same backing structure as the unbounded, but drops messages to deadletter on overflow. 
So if the bounds of this queue is 1000, then when you try to post a message to it when length is > 1000, drop the message. 
(coming up with a good default for that queue size might be hard though)

One could think that blocking would be a better choice, which it might be inprocess. but if the Remote endpoint reader tries to post to a full queue and blocks, you are now blocking the endpoint reader.

Having a bounded mailbox as the default is a no-go as that is blocking on overflow, and consumes a lot of memory all the time.

Other areas to consider on this topic?

**Comment by cpx86** [comment]
> Kill after x restarts or exponential back-off ?
Both? Transient errors such as temporary network errors should usually be resolved after a few retries with backoff, but in case of a long outage you wouldn't want to retry indefinitely. And if the actor fails due to a non-transient error (e.g. logic error) you definitely don't want to keep retrying.

> we should introduce a new queue, built on the same backing structure as the unbounded, but drops messages to deadletter on overflow
What about message ordering and delivery guarantees? E.g. if messages 1,2,3 are sent to an actor, but only messages 1,3 arrive and 2 ends up on dead-letter - if the actor is dependent on processing message 2 in order to process message 3, how should it react?
